In [1]:
import pandas as pd
dataset = pd.read_csv("50_Startups.csv")

In [2]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [3]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
y = dataset["Profit"]

In [6]:
y = y.values

In [7]:
X = dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]

In [8]:
X = X.values

In [9]:
state = dataset["State"]

In [10]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
state_le = LabelEncoder()
state = state_le.fit_transform(state)

In [11]:
state

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [12]:
state = state.reshape(-1,1)
state.shape

(50, 1)

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
state_ohe = OneHotEncoder()

In [15]:
state = state_ohe.fit_transform(state)

In [16]:
state

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [17]:
type(state)

scipy.sparse.csr.csr_matrix

In [18]:
state = state.toarray()

In [19]:
state[:5]

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [24]:
# Solve Dummy variable Trap
state = state[:,:2]

In [26]:
import numpy as np
X = np.hstack((X[:,:3], state))

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
model = LinearRegression()

In [29]:
model.fit(X,y)

LinearRegression()

In [30]:
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  4.18870191e+01,
        2.40675812e+02])

In [31]:
model.intercept_

50083.45681250352